# Generated by Django 4.2.11 on 2024-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=120)),
                ("contact_number", models.TextField(max_length=120)),
                ("date", models.DateField()),
                ("party_size", models.IntegerField()),
                ("additional_information", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Starter", "Starter"),
                            ("Mains", "Mains"),
                            ("Desserts", "Desserts"),
                            ("Drinks", "Drinks"),
                        ],
                        default="Starter",
                        max_length=20,
                    ),
                ),
                ("title", models.TextField(max_length=120)),
                ("desc", models.TextField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=120)),
                ("contact_number", models.TextField(max_length=120)),
                ("date", models.DateField()),
                ("party_size", models.IntegerField()),
                ("additional_information", models.TextField(max_length=500)),
            ],
        ),
    ]
