# Generated by Django 4.2.11 on 2024-04-19 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="menu",
            new_name="menu_items",
        ),
    ]
