# Generated by Django 4.2.11 on 2024-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_menu_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu_items",
            name="price",
            field=models.IntegerField(),
        ),
    ]
