# Generated by Django 4.2.11 on 2024-04-19 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_rename_name_feedback_u_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="feedback",
        ),
    ]
