# Generated by Django 4.2.11 on 2024-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("contact_number", models.CharField(max_length=120)),
                ("date", models.DateField()),
                ("feedback", models.TextField(max_length=500)),
            ],
        ),
    ]
