# Generated by Django 4.2.11 on 2024-04-19 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback",
            new_name="feedback_model",
        ),
    ]
